#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyPriceFetch
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="oom_proxy")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::ProxyPriceFetch.Properties.Settings.Default.oom_proxyConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<artikli> artiklis
		{
			get
			{
				return this.GetTable<artikli>();
			}
		}
		
		public System.Data.Linq.Table<korisnici> korisnicis
		{
			get
			{
				return this.GetTable<korisnici>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.artikli")]
	public partial class artikli
	{
		
		private int _proizvodID;
		
		private string _nazivProizvoda;
		
		private System.Nullable<decimal> _jedinicnaCijena;
		
		public artikli()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proizvodID", DbType="Int NOT NULL")]
		public int proizvodID
		{
			get
			{
				return this._proizvodID;
			}
			set
			{
				if ((this._proizvodID != value))
				{
					this._proizvodID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazivProizvoda", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string nazivProizvoda
		{
			get
			{
				return this._nazivProizvoda;
			}
			set
			{
				if ((this._nazivProizvoda != value))
				{
					this._nazivProizvoda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jedinicnaCijena", DbType="Money")]
		public System.Nullable<decimal> jedinicnaCijena
		{
			get
			{
				return this._jedinicnaCijena;
			}
			set
			{
				if ((this._jedinicnaCijena != value))
				{
					this._jedinicnaCijena = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.korisnici")]
	public partial class korisnici
	{
		
		private int _ID;
		
		private string _ime;
		
		private string _prezime;
		
		private string _userID;
		
		public korisnici()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ime", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ime
		{
			get
			{
				return this._ime;
			}
			set
			{
				if ((this._ime != value))
				{
					this._ime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prezime", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string prezime
		{
			get
			{
				return this._prezime;
			}
			set
			{
				if ((this._prezime != value))
				{
					this._prezime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userID", DbType="NVarChar(20)")]
		public string userID
		{
			get
			{
				return this._userID;
			}
			set
			{
				if ((this._userID != value))
				{
					this._userID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
